= Trie
:icons: font

[Overview of Trie%collapsible]
Tries are tree data structures used to store and search keys from a set, which are usually strings stored character-by-character.  Each node of trie corresponds to single character. 

.Key characteristics of Trie:
====
1. Order of characters represented as edges between adjacent nodes, e.g., in “are” an edge from node `a` to node `r` to node `e`: Node `a` as parent of node `r`, and node `r` as parent of node `e`.
2. Level of nodes signal position of characters within word. Each level corresponds to specified index in represented word, e.g., nodes correspond to distinct character in trie's stored words. Traversing from root to leaf node, characters encountered spell word associated with path.
3. Contains end-of-word nodes to mark conclusion of word. End-of-word nodes indicate termination point for stored word, and is crucial for efficient word retrieval and validation operations since it enables tries to distinguish between prefixes and complete words during searches and insertions and additional space not required to store strings with common prefixes, and searches can be performed using dfs and following edges between nodes. 
4. Words with same prefix or stem share memory area that corresponds to prefix.
====

[discrete]
== Staple Methods of Trie
1. `Insert(word)`: Start at root and traverse down, creating new nodes when required for characters in string. Time complexity is 
`O(m)`, where m is length of word. 
2. `Search(word)`: Start at root and traverse down, following path corresponding to characters of target word. If `pointer == null` or reaches end of word before arriving at leaf node, word is not present in trie. Time complexity is `O(m)`.
3. `Delete(word)`: Start at root and traverse down, following path corresponding to characters of target word. If found, remove nodes corresponding to characters of string. May also include cleanup remove unnecessary nodes and maintain trie’s efficiency. Time complexity is `O(m)`, where `m` is length of word.

.Trie's More Efficient than Binary Tree for Storing and Searching Strings
====
Time complexity of binary tree is `O(logn)`, where log is base 2.
In quaternary tree, every node fans-out by four and each node can have four children. Time complexity of this tree is `O(logn)`, where `log` is base 4, which is an improvement in performance even though it’s only by a constant factor. As trees become wider and shorter, operations become more efficient since traversals become less deep. Consider an n-ary tree where nodes can have `n` children and `n` is number of unique values in dataset. Time complexity is `O(logn)`, where `log` is base `n`, making tree wider and shorter and maximum depth equal to maximum length of word or string.
====

== Characteristics of Trie
***
:tip-caption: 💡
ifdef::env-github[]
:tip-caption: :bulb:
endif::env-github[]
ifdef::env-asciidoctor[]
:tip-caption: :bulb:
endif::env-asciidoctor[]

TIP: Use when problem matches criteria outlined below.

[unordered]
*Partial Matches*:: [.small]#Compares 2 strings to detect partial matching.#
*Space Optimization*:: [.small]#Calls for space optimization on dictionary or other word store.#
*String can be broken down*:: [.small]#Problem allows strings to be broken down into characters.#
***

== Problems Solved Using Trie
link:LongestCommonPrefix.java[Longest Common Prefix]:: [.small]#finding longest common prefix of given strings.#
link:CountUniqueWords.java[Count Unique Words]:: [.small]#counting number of unique words in a given string.#
link:ImplementTrie.java[Implement Trie]:: [.small]#implementing a trie data structure.#
link:SearchSuggestionsSystem.java[Search Suggestions System]:: [.small]#finding search suggestions for a given prefix.#
link:ReplaceWords.java[Replace Words]:: [.small]#replacing words in a given string with their shortest unique prefix.#
link:DesignAddAndSearchWordsDataStructure.java[Design Add and Search Words Data Structure]:: [.small]#designing a data structure that can add and search words.#
link:WordSearchII.java[Word Search II]:: [.small]#finding all words in a grid of characters.#
link:TopKFrequentWords.java[Top K Frequent Words]:: [.small]#finding top k frequent words in a given string.#
link:IndexPairsOfString.java[Index Pairs of String]:: [.small]#finding all index pairs of a given string in a given text.#
link:LexicographicalNumbers.java[Lexicographical Numbers]:: [.small]#finding lexicographical numbers in a given range.#

== Real World Applications of Trie
*Autocomplete System*:: [.small]#Search engine autocomplete is feature that prompts search engine to suggest words to complete a user's query and are given based on common queries matching prefix of already-typed string.#
*Orthographic Corrector*:: [.small]#Spell checking systems that provide suggestions for misspelled words.#
*Prefix Matching in IP Addresses or URLs*:: [.small]#IP prefixes and URLs stored in trie so that firewalls and security devices can quickly match incoming requests against set of allowed or blocked prefixes.#